import { ArrowRight, CircleDollarSign, Settings, ShoppingBag, WalletCards } from 'lucide-react';

<<<<<<< HEAD
import { ArrowRight, Boxes, CalendarDays, Settings, ShoppingBag, SlidersHorizontal, SquareStack, WalletCards } from 'lucide-react';
import { AdminShell } from '@/components/admin-shell';
const cards = [{ href: '/admin/pedidos', title: 'Pedidos', text: 'Acompanhe a fila e atualize o preparo.', icon: ShoppingBag, color: 'bg-[#b5232b]' }, { href: '/admin/reservas', title: 'Agenda', text: 'Confirme reservas e acompanhe a ocupação.', icon: CalendarDays, color: 'bg-[#e3262e]' }, { href: '/admin/mesas', title: 'Mesas', text: 'Cadastre capacidade e evite choques de horário.', icon: SquareStack, color: 'bg-[#c7a773] text-[#070a08]' }, { href: '/admin/catalogo', title: 'Catálogo', text: 'Produtos, tamanhos, preços e categorias.', icon: Boxes, color: 'bg-[#c7a773] text-[#070a08]' }, { href: '/admin/promocoes', title: 'Promoções', text: 'Crie ofertas para destacar no cardápio.', icon: SlidersHorizontal, color: 'bg-[#8b1e2b]' }, { href: '/admin/financas', title: 'Finanças', text: 'Acompanhe vendas, insumos e despesas.', icon: WalletCards, color: 'bg-[#d6e7bf] text-[#070a08]' }, { href: '/admin/adicionais', title: 'Adicionais', text: 'Grupos, limites, premium e disponibilidade.', icon: SlidersHorizontal, color: 'bg-[#d6e7bf] text-[#070a08]' }, { href: '/admin/configuracoes', title: 'Loja', text: 'Horário, delivery, pagamentos e WhatsApp.', icon: Settings, color: 'bg-[#070a08]' }];
export default function AdminDashboard() { return <AdminShell><div className="flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#8b1e2b]">Painel</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Visão geral</h1><p className="mt-2 text-sm text-[#7b887d]">Tudo que a equipe precisa para operar os pedidos.</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{cards.map(({ href, title, text, icon: Icon, color }) => <a key={href} href={href} className="group rounded-[26px] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className={`grid size-11 place-items-center rounded-2xl text-white ${color}`}><Icon className="size-5" /></span><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-1 text-sm text-[#7b887d]">{text}</p><span className="mt-5 flex items-center gap-2 text-sm font-black text-[#b5232b]">Abrir <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></a>)}</div></AdminShell>; }
=======
import { AdminShell } from '@/components/admin-shell';

const cards = [
  { href: '/admin/pedidos', title: 'Pedidos', text: 'Acompanhe a fila e atualize o preparo.', icon: ShoppingBag, color: 'bg-[#172d3d]' },
  { href: '/admin/caixa', title: 'Caixa', text: 'Abra o turno, registre movimentações e feche o caixa.', icon: WalletCards, color: 'bg-[#f1c46a] text-[#172d3d]' },
  { href: '/admin/financeiro', title: 'Financeiro', text: 'Consulte vendas, pagamentos, estornos e indicadores.', icon: CircleDollarSign, color: 'bg-[#dceef1] text-[#172d3d]' },
  { href: '/admin/catalogo', title: 'Cardápio', text: 'Produtos, porções, preços e categorias.', icon: ShoppingBag, color: 'bg-[#dbe8ee] text-[#172d3d]' },
  { href: '/admin/configuracoes', title: 'Configurações', text: 'Horários, delivery, pagamentos e dados da loja.', icon: Settings, color: 'bg-[#23475a]' },
];
export default function AdminDashboard() { return <AdminShell><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#b07a2e]">Teiko Sushi</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Visão geral</h1><p className="mt-2 text-sm text-[#607681]">Pedidos, operação de caixa e financeiro em um só painel.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ href, title, text, icon: Icon, color }) => <a key={href} href={href} className="group rounded-[26px] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className={`grid size-11 place-items-center rounded-2xl ${color}`}><Icon className="size-5" /></span><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-1 text-sm text-[#607681]">{text}</p><span className="mt-5 flex items-center gap-2 text-sm font-black text-[#23475a]">Abrir <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></a>)}</div></AdminShell>; }
>>>>>>> origin/main
