import type {Artwork,Customer,DemoState,Material,Matrix,Order,OrderItem,Quote,Stage,Priority} from './domain';
const iso=(base:Date,offset:number)=>{const d=new Date(base);d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const item=(id:string,description:string,quantity:number,completed:number,spec:Partial<OrderItem['spec']>,extra:Partial<OrderItem>={}):OrderItem=>({id,description,productType:description,quantity,completed,sizes:{},garmentColor:'Natural',source:'studio',personalizations:[],spec:{placement:'Peito esquerdo',width:8,height:5,colors:['Verde 1847'],stitches:8200,hoop:'12 × 12 cm',material:'Piquet',...spec},...extra});
export function createSeed(now=new Date()):DemoState{
 const customers:Customer[]=[
  {id:'c1',name:'Paula Nogueira',phone:'(11) 90000-0101',city:'Campinas',type:'consumer',createdAt:iso(now,-120)},
  {id:'c2',name:'Renato Lima',company:'Horizonte Uniformes',phone:'(11) 90000-0102',city:'Jundiaí',type:'business',createdAt:iso(now,-430),notes:'Cliente recorrente; confirmar grade antes de produzir.'},
  {id:'c3',name:'Marta Reis',company:'Clube Aurora',phone:'(11) 90000-0103',city:'Valinhos',type:'business',createdAt:iso(now,-250)},
  {id:'c4',name:'Bianca Teles',phone:'(11) 90000-0104',city:'Campinas',type:'consumer',createdAt:iso(now,-80)},
  {id:'c5',name:'Davi Campos',company:'Café Cedro',phone:'(11) 90000-0105',city:'Vinhedo',type:'business',createdAt:iso(now,-310)},
  {id:'c6',name:'Elisa Moura',phone:'(11) 90000-0106',city:'Sumaré',type:'consumer',createdAt:iso(now,-35)},
  {id:'c7',name:'Caio Prado',company:'Trilha Viva',phone:'(11) 90000-0107',city:'Campinas',type:'business',createdAt:iso(now,-190)},
  {id:'c8',name:'Nina Ferraz',phone:'(11) 90000-0108',city:'Hortolândia',type:'consumer',createdAt:iso(now,-22)},
  {id:'c9',name:'Otávio Luz',company:'Escola Ipê',phone:'(11) 90000-0109',city:'Americana',type:'business',createdAt:iso(now,-520)},
  {id:'c10',name:'Lara Mendonça',phone:'(11) 90000-0110',city:'Campinas',type:'consumer',createdAt:iso(now,-11)}];
 const matrices:Matrix[]=['Logo Horizonte','Brasão Aurora','Urso Helena','Monograma LM','Logo Café Cedro','Trilha Viva','Brasão Ipê','Ramo Botânico','Clube 10 anos','Monograma PR'].map((name,index)=>({id:`m${index+1}`,name,customerId:index<7?`c${[2,3,1,10,5,7,9][index]}`:undefined,width:[8,6.5,9,5,7,8.5,6,10,7.5,5.5][index],height:[4,6.5,7,5,6,5,6,4,7.5,5][index],stitches:[8420,11240,13780,5640,9220,10480,12500,7600,14900,6100][index],colors:['#1f6f63','#d97d48','#e2b5b0'].slice(0,index%3+1),hoop:index%2?'15 × 15 cm':'12 × 12 cm',formats:['DST','PES','EXP'],status:index===8?'review':'ready',createdAt:iso(now,-200-index*13),lastUsedAt:iso(now,-index*8),compatibility:'Confirmar tamanho, tecido e estabilizador antes de reutilizar.',uses:index<7?[`o${index+1}`]:[]}));
 const orders:Order[]=[];
 const add=(id:string,number:number,customerId:string,days:number,priority:Priority,status:Stage,items:OrderItem[],total:number,paid:number,delivery:Order['delivery'],source:Order['source']='WhatsApp')=>orders.push({id,number,customerId,createdAt:iso(now,-5),promisedAt:iso(now,days),priority,status,items,total,paid,delivery,source,activity:[{id:`ev-${id}`,at:new Date().toISOString(),label:'Pedido inserido na demonstração'}]});
 add('o1',1047,'c1',2,'high','ready',[item('i1','Toalha de banho',1,0,{placement:'Barra central',width:15,height:8,colors:['Rosa 1120','Marrom 1065'],stitches:13780,hoop:'18 × 13 cm',material:'Felpa',stabilizer:'Hidrossolúvel'},{garmentColor:'Rosa blush',personalizations:[{id:'p1',text:'Helena',font:'Script',threadColor:'Rosa 1120'}],artworkId:'a1',matrixId:'m3'}),item('i2','Toalha de boca',2,0,{placement:'Barra',width:9,height:5,colors:['Rosa 1120'],stitches:5200,material:'Felpa'},{garmentColor:'Rosa blush'})],286,100,{mode:'Retirada',status:'Pendente'});
 add('o2',1048,'c2',0,'urgent','production',[item('i3','Polo corporativa',30,18,{placement:'Peito esquerdo',width:8,height:4,colors:['Verde 1847','Dourado 1170','Branco'],stitches:8420,material:'Piquet'},{sizes:{P:6,M:12,G:8,GG:4},garmentColor:'Grafite',matrixId:'m1',personalizations:[{id:'p2',text:'Ana',role:'Comercial',size:'M',font:'Sans',threadColor:'Branco'},{id:'p3',text:'Bruno',role:'Técnico',size:'G',font:'Sans',threadColor:'Branco'},{id:'p4',text:'Carla',role:'Gestão',size:'P',font:'Sans',threadColor:'Branco'}]})],2850,1425,{mode:'Entrega local',status:'Pendente'},'Recorrente');
 add('o3',1052,'c3',4,'high','digitizing',[item('i4','Boné estruturado',50,0,{placement:'Frente',width:10,height:5.5,colors:['Azul marinho','Dourado'],stitches:10800,hoop:'Bastidor para boné',material:'Brim'},{garmentColor:'Azul marinho',artworkId:'a2'})],2300,700,{mode:'Envio',status:'Pendente',carrier:'Transportadora demonstrativa'},'Orçamento');
 const names=['Ana','Beatriz','Carlos','Daniela','Edu','Fábia','Gabi','Heitor','Iara','João','Lia','Mauro'];
 add('o4',1045,'c4',0,'normal','done',[item('i5','Toalha lavabo',12,12,{placement:'Barra',width:8,height:3.5,colors:['Rosa','Lilás','Azul'],stitches:3600,material:'Felpa'},{personalizations:names.map((text,index)=>({id:`pt${index}`,text,font:index%3===0?'Serif':'Script',threadColor:['Rosa','Lilás','Azul'][index%3]}))})],720,720,{mode:'Retirada',status:'Pronto'});
 add('o5',1053,'c6',1,'urgent','approval',[item('i6','Jaqueta jeans',1,0,{placement:'Costas',width:26,height:31,colors:['Terracota','Creme','Verde'],stitches:48600,hoop:'30 × 40 cm',material:'Jeans',stabilizer:'Recorte pesado'},{source:'customer',garmentColor:'Jeans médio',artworkId:'a3'})],690,250,{mode:'Retirada',status:'Pendente'});
 add('o6',1040,'c5',7,'normal','ready',[item('i7','Avental de barista',18,0,{placement:'Peito',width:7,height:6,colors:['Verde 1847','Creme'],stitches:9220,material:'Sarja'},{garmentColor:'Areia',matrixId:'m5'})],1530,765,{mode:'Entrega local',status:'Pendente'},'Recorrente');
 add('o7',1054,'c7',5,'normal','art',[item('i8','Camiseta de trilha',24,0,{placement:'Manga direita',width:8.5,height:5,colors:['Verde','Laranja'],stitches:10480,material:'Dry fit'},{matrixId:'m6'})],1680,500,{mode:'Envio',status:'Pendente'},'Indicação');
 add('o8',1049,'c9',-1,'high','finishing',[item('i9','Moletom escolar',20,19,{placement:'Peito esquerdo',width:6,height:6,colors:['Verde','Amarelo'],stitches:12500,material:'Moletom'},{sizes:{P:4,M:8,G:6,GG:2},matrixId:'m7'})],2400,1800,{mode:'Entrega local',status:'Pendente'},'Recorrente');
 add('o9',1055,'c8',9,'normal','confirmation',[item('i10','Necessaire',8,0,{placement:'Centro',width:9,height:4,colors:['Terracota'],stitches:5800,material:'Lona'},{garmentColor:'Cru'})],640,0,{mode:'Retirada',status:'Pendente'});
 add('o10',1038,'c2',-12,'normal','delivered',[item('i11','Camisa social',16,16,{placement:'Peito esquerdo',width:8,height:4,colors:['Verde 1847'],stitches:8420,material:'Tricoline'},{matrixId:'m1'})],1760,1760,{mode:'Entrega local',status:'Entregue'},'Recorrente');
 add('o11',1050,'c10',3,'normal','approval',[item('i12','Robe de noiva',2,0,{placement:'Costas',width:18,height:8,colors:['Champagne'],stitches:15200,material:'Cetim'},{personalizations:[{id:'pr1',text:'Lara',font:'Script',threadColor:'Champagne'},{id:'pr2',text:'Mãe da noiva',font:'Script',threadColor:'Champagne'}],artworkId:'a4',matrixId:'m4'})],520,260,{mode:'Retirada',status:'Pendente'});
 add('o12',1046,'c9',6,'normal','production',[item('i13','Polo coordenação',10,6,{placement:'Peito esquerdo',width:6,height:6,colors:['Verde','Amarelo'],stitches:12500,material:'Piquet'},{sizes:{P:2,M:4,G:3,GG:1},matrixId:'m7'})],1180,590,{mode:'Entrega local',status:'Pendente'},'Recorrente');
 const artworks:Artwork[]=[{id:'a1',orderItemId:'i1',status:'approved',versions:[{id:'a1v1',number:1,type:'original',fileName:'urso-referencia.jpg',format:'JPG',createdAt:iso(now,-6),status:'changes'},{id:'a1v2',number:2,type:'proof',fileName:'prova-urso-v2.pdf',format:'PDF',createdAt:iso(now,-4),status:'approved'},{id:'a1v3',number:3,type:'digitized-preview',fileName:'teste-pontos-v3.png',format:'PNG',createdAt:iso(now,-2),status:'draft'}],currentVersionId:'a1v3',approvedVersionId:'a1v2',changes:[{id:'ch1',fromVersionId:'a1v1',at:iso(now,-5),text:'Suavizar o contorno do urso.',resolvedByVersionId:'a1v2'}]},{id:'a2',orderItemId:'i4',status:'digitizing',versions:[{id:'a2v1',number:1,type:'original',fileName:'brasao-referencia.pdf',format:'PDF',createdAt:iso(now,-3),status:'draft'}],currentVersionId:'a2v1',changes:[]},{id:'a3',orderItemId:'i6',status:'awaiting',versions:[{id:'a3v1',number:1,type:'proof',fileName:'costas-jaqueta-v1.pdf',format:'PDF',createdAt:iso(now,-2),status:'sent'}],currentVersionId:'a3v1',changes:[]},{id:'a4',orderItemId:'i12',status:'awaiting',versions:[{id:'a4v1',number:1,type:'proof',fileName:'robe-lara-v1.pdf',format:'PDF',createdAt:iso(now,-1),status:'sent'}],currentVersionId:'a4v1',changes:[]}];
 const quotes:Quote[]=[{id:'q1',number:3021,customerId:'c5',createdAt:iso(now,-2),validUntil:iso(now,5),status:'approved',description:'24 aventais com logo no peito',quantity:24,digitizingFee:0,urgencyFee:0,shippingFee:80,discount:60,total:2060,notes:'Reutilizar produto Café Cedro.'},{id:'q2',number:3022,customerId:'c3',createdAt:iso(now,-1),validUntil:iso(now,7),status:'sent',description:'40 bonés para evento anual',quantity:40,digitizingFee:180,urgencyFee:0,shippingFee:70,discount:0,total:2110},{id:'q3',number:3018,customerId:'c8',createdAt:iso(now,-5),validUntil:iso(now,2),status:'draft',description:'10 nécessaires com iniciais',quantity:10,digitizingFee:120,urgencyFee:0,shippingFee:0,discount:0,total:780},{id:'q4',number:3017,customerId:'c9',createdAt:iso(now,-6),validUntil:iso(now,1),status:'sent',description:'35 polos equipe pedagógica',quantity:35,digitizingFee:0,urgencyFee:0,shippingFee:60,discount:100,total:3710},{id:'q5',number:3015,customerId:'c7',createdAt:iso(now,-9),validUntil:iso(now,-2),status:'converted',description:'24 camisetas Trilha Viva',quantity:24,digitizingFee:0,urgencyFee:0,shippingFee:0,discount:0,total:1680,convertedOrderId:'o7'},{id:'q6',number:3024,customerId:'c10',createdAt:iso(now,0),validUntil:iso(now,10),status:'draft',description:'6 toalhas presenteáveis',quantity:6,digitizingFee:90,urgencyFee:0,shippingFee:0,discount:0,total:480}];
 const materials:Material[]=[['Linha','L-1847','Verde floresta','cone',5,3,'#1f6f63'],['Linha','L-1120','Rosa blush','cone',2,3,'#d99b9b'],['Linha','L-1170','Dourado','cone',4,2,'#c4a14a'],['Linha','L-1065','Marrom urso','cone',1,2,'#795548'],['Linha','L-0900','Branco','cone',8,3,'#eee'],['Linha','L-2210','Azul marinho','cone',6,2,'#23395d'],['Linha','L-3301','Terracota','cone',3,2,'#c66b47'],['Peça em branco','PB-POLO-G','Polo grafite','un.',12,10],['Peça em branco','PB-BONE-AZ','Boné azul','un.',55,20],['Peça em branco','PB-TOA-RS','Toalha rosa','un.',7,8],['Insumo','ES-REC-M','Estabilizador recorte médio','m',18,10],['Insumo','ES-HID','Hidrossolúvel','m',6,8],['Insumo','AG-75','Agulha 75/11','un.',20,12],['Insumo','BOB-90','Bobina branca','un.',9,10]].map((x,index)=>({id:`mat${index+1}`,category:x[0] as Material['category'],code:x[1] as string,name:x[2] as string,unit:x[3] as string,stock:x[4] as number,minimum:x[5] as number,color:x[6] as string|undefined}));
 return {version:2,seededAt:new Date().toISOString(),customers,orders,artworks,matrices,quotes,materials};
}
