'use client';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {createSeed} from './seed';
import {validateState,type DemoState,type Order,type OrderItem,type Quote,type Stage} from './domain';

const STORAGE_KEY='estudio-cor-demo-v2-release';
type Store={state:DemoState;storageOk:boolean;toast:string;clearToast:()=>void;reset:()=>void;createOrder:(data:{customerId:string;description:string;quantity:number;secondDescription?:string;secondQuantity?:number;promisedAt:string;total:number;matrixId?:string})=>Order;updateOrder:(order:Order)=>void;moveOrder:(id:string,stage:Stage)=>void;updateProduction:(orderId:string,itemId:string,completed:number)=>void;repeatOrder:(id:string)=>Order|undefined;addPersonalization:(orderId:string,itemId:string,text:string)=>void;linkMatrix:(orderId:string,itemId:string,matrixId:string)=>void;addArtVersion:(artId:string)=>void;requestChange:(artId:string,text:string)=>void;approveArtwork:(artId:string)=>void;recordPayment:(orderId:string,amount:number)=>void;markReady:(orderId:string)=>void;completeDelivery:(orderId:string)=>void;createQuote:(data:{customerId:string;description:string;quantity:number;total:number})=>Quote;approveQuote:(id:string)=>void;convertQuote:(id:string)=>Order|undefined};
const Ctx=createContext<Store|null>(null);
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const activity=(label:string)=>({id:id('ev'),at:new Date().toISOString(),label});

export function DemoProvider({children}:{children:ReactNode}){
 const [storageOk,setStorageOk]=useState(true);const [toast,setToast]=useState('');
 const [state,setState]=useState<DemoState>(()=>createSeed());
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(validateState(parsed))window.setTimeout(()=>setState(parsed),0);else localStorage.setItem(STORAGE_KEY,JSON.stringify(createSeed()));}}catch{window.setTimeout(()=>setStorageOk(false),0)}},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{window.setTimeout(()=>setStorageOk(false),0)}},[state]);
 const say=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),3200)};
 const updateOrder=(order:Order)=>setState(s=>({...s,orders:s.orders.map(o=>o.id===order.id?order:o)}));
 const createOrder:Store['createOrder']=(data)=>{const number=Math.max(...state.orders.map(o=>o.number))+1;const makeItem=(description:string,quantity:number,index:number):OrderItem=>({id:id('item'),description,productType:description,quantity,completed:0,sizes:{},garmentColor:'A definir',source:'studio',personalizations:[],matrixId:index===0?data.matrixId:undefined,spec:{placement:'Peito esquerdo',width:8,height:5,colors:['A definir'],stitches:data.matrixId?state.matrices.find(m=>m.id===data.matrixId)?.stitches||0:0,hoop:'A confirmar',material:'A confirmar'}});const items=[makeItem(data.description,data.quantity,0)];if(data.secondDescription&&data.secondQuantity)items.push(makeItem(data.secondDescription,data.secondQuantity,1));const created:Order={id:id('order'),number,customerId:data.customerId,createdAt:new Date().toISOString().slice(0,10),promisedAt:data.promisedAt,priority:'normal',source:'WhatsApp',status:data.matrixId?'ready':'art',items,total:data.total,paid:0,delivery:{mode:'Retirada',status:'Pendente'},activity:[activity('Pedido criado na demonstração')]};setState(s=>({...s,orders:[created,...s.orders],matrices:s.matrices.map(m=>m.id===data.matrixId?{...m,lastUsedAt:new Date().toISOString().slice(0,10),uses:[...m.uses,created.id]}:m)}));say(`Pedido #${created.number} criado`);return created};
 const moveOrder=(orderId:string,stage:Stage)=>setState(s=>({...s,orders:s.orders.map(o=>o.id===orderId?{...o,status:stage,activity:[activity(`Movido para ${stage}`),...o.activity]}:o)}));
 const updateProduction=(orderId:string,itemId:string,completed:number)=>setState(s=>({...s,orders:s.orders.map(o=>{if(o.id!==orderId)return o;const items=o.items.map(i=>i.id===itemId?{...i,completed:Math.max(0,Math.min(i.quantity,completed))}:i);const allDone=items.every(i=>i.completed===i.quantity);return {...o,items,status:allDone?'finishing':o.status,activity:[activity(allDone?'Produção concluída; enviado para acabamento':'Progresso de produção atualizado'),...o.activity]}})}));
 const repeatOrder=(orderId:string)=>{const source=state.orders.find(o=>o.id===orderId);if(!source)return;const clone:Order={...source,id:id('order'),number:Math.max(...state.orders.map(o=>o.number))+1,createdAt:new Date().toISOString().slice(0,10),promisedAt:new Date(Date.now()+7*86400000).toISOString().slice(0,10),status:'confirmation',paid:0,source:'Recorrente',items:source.items.map(i=>({...i,id:id('item'),completed:0,personalizations:[]})),delivery:{...source.delivery,status:'Pendente'},activity:[activity(`Pedido repetido a partir de #${source.number}`)]};setState(s=>({...s,orders:[clone,...s.orders]}));say('Rascunho recorrente criado com produto disponível');return clone};
 const addPersonalization=(orderId:string,itemId:string,text:string)=>setState(s=>({...s,orders:s.orders.map(o=>o.id!==orderId?o:{...o,items:o.items.map(i=>i.id!==itemId||i.personalizations.length>=i.quantity?i:{...i,personalizations:[...i.personalizations,{id:id('p'),text,font:'Script',threadColor:'A definir'}]})})}));
 const linkMatrix=(orderId:string,itemId:string,matrixId:string)=>setState(s=>({...s,orders:s.orders.map(o=>o.id!==orderId?o:{...o,items:o.items.map(i=>i.id!==itemId?i:{...i,matrixId,spec:{...i.spec,stitches:s.matrices.find(m=>m.id===matrixId)?.stitches||i.spec.stitches}}),activity:[activity('Produto existente vinculada'),...o.activity]}),matrices:s.matrices.map(m=>m.id===matrixId?{...m,lastUsedAt:new Date().toISOString().slice(0,10),uses:Array.from(new Set([...m.uses,orderId]))}:m)}));
 const addArtVersion=(artId:string)=>setState(s=>({...s,artworks:s.artworks.map(a=>{if(a.id!==artId)return a;const number=Math.max(...a.versions.map(v=>v.number))+1;const version={id:id('version'),number,type:'proof' as const,fileName:`prova-v${number}.pdf`,format:'PDF',createdAt:new Date().toISOString().slice(0,10),status:'draft' as const};return {...a,currentVersionId:version.id,status:'proof',versions:[...a.versions,version]}})}));
 const requestChange=(artId:string,text:string)=>setState(s=>({...s,artworks:s.artworks.map(a=>a.id===artId?{...a,status:'changes',versions:a.versions.map(v=>v.id===a.currentVersionId?{...v,status:'changes'}:v),changes:[...a.changes,{id:id('change'),fromVersionId:a.currentVersionId,at:new Date().toISOString().slice(0,10),text}]}:a)}));
 const approveArtwork=(artId:string)=>setState(s=>({...s,artworks:s.artworks.map(a=>a.id===artId?{...a,status:'approved',approvedVersionId:a.currentVersionId,versions:a.versions.map(v=>v.id===a.currentVersionId?{...v,status:'approved'}:v)}:a),orders:s.orders.map(o=>o.items.some(i=>i.artworkId===artId)?{...o,status:o.status==='approval'?'ready':o.status,activity:[activity('Versão de arte aprovada'),...o.activity]}:o)}));
 const recordPayment=(orderId:string,amount:number)=>setState(s=>({...s,orders:s.orders.map(o=>o.id===orderId?{...o,paid:Math.min(o.total,o.paid+Math.max(0,amount)),activity:[activity('Pagamento operacional registrado'),...o.activity]}:o)}));
 const markReady=(orderId:string)=>moveOrder(orderId,'done');
 const completeDelivery=(orderId:string)=>setState(s=>({...s,orders:s.orders.map(o=>o.id===orderId?{...o,status:'delivered',delivery:{...o.delivery,status:'Entregue'},activity:[activity('Entrega concluída'),...o.activity]}:o)}));
 const createQuote:Store['createQuote']=(data)=>{const quote:Quote={id:id('quote'),number:Math.max(...state.quotes.map(q=>q.number))+1,customerId:data.customerId,createdAt:new Date().toISOString().slice(0,10),validUntil:new Date(Date.now()+7*86400000).toISOString().slice(0,10),status:'draft',description:data.description,quantity:data.quantity,digitizingFee:0,urgencyFee:0,shippingFee:0,discount:0,total:data.total};setState(s=>({...s,quotes:[quote,...s.quotes]}));say(`Orçamento #${quote.number} criado`);return quote};
 const approveQuote=(quoteId:string)=>setState(s=>({...s,quotes:s.quotes.map(q=>q.id===quoteId?{...q,status:'approved'}:q)}));
 const convertQuote=(quoteId:string)=>{const quote=state.quotes.find(q=>q.id===quoteId);if(!quote||quote.convertedOrderId)return;const order=createOrder({customerId:quote.customerId,description:quote.description,quantity:quote.quantity,promisedAt:new Date(Date.now()+10*86400000).toISOString().slice(0,10),total:quote.total});setState(s=>({...s,orders:s.orders.map(o=>o.id===order.id?{...o,source:'Orçamento',sourceQuoteId:quoteId}:o),quotes:s.quotes.map(q=>q.id===quoteId?{...q,status:'converted',convertedOrderId:order.id}:q)}));say(`Orçamento convertido no pedido #${order.number}`);return order};
 const reset=()=>{const fresh=createSeed();try{localStorage.removeItem(STORAGE_KEY)}catch{setStorageOk(false)}setState(fresh);say('Dados da demonstração restaurados')};
 const value:Store={state,storageOk,toast,clearToast:()=>setToast(''),reset,createOrder,updateOrder,moveOrder,updateProduction,repeatOrder,addPersonalization,linkMatrix,addArtVersion,requestChange,approveArtwork,recordPayment,markReady,completeDelivery,createQuote,approveQuote,convertQuote};
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export const useDemo=()=>{const value=useContext(Ctx);if(!value)throw new Error('DemoProvider ausente');return value};
