const fourSizes = (prices) => ['300ml', '400ml', '500ml', '700ml'].map((id, index) => ({
  id,
  label: id.replace('ml', ' ml'),
  active: true,
  basePriceCents: prices[index],
  displayOrder: index + 1,
}));

const threeSizes = (prices, includedModifiersCount) => ['300ml', '400ml', '500ml'].map((id, index) => ({
  id,
  label: id.replace('ml', ' ml'),
  active: true,
  basePriceCents: prices[index],
  ...(includedModifiersCount === undefined ? {} : { includedModifiersCount }),
  displayOrder: index + 1,
}));

const accompanimentGroupIds = [
  'mousses',
  'suplementos',
  'frutas',
  'coberturas',
  'sorvetes-adicionais',
  'granola',
  'chocolates',
  'diversos',
];

const combo = (id, name, description, prices, displayOrder, note) => ({
  id,
  name,
  slug: id,
  description: note ? `${description}. ${note}` : description,
  active: true,
  categoryId: 'combinados',
  productType: 'CUSTOMIZABLE',
  displayOrder,
  sizes: fourSizes(prices),
  modifierGroupIds: [...accompanimentGroupIds, 'embalagem'],
});

const simple = (id, name, description, categoryId, label, price, displayOrder) => ({
  id,
  name,
  slug: id,
  description,
  active: true,
  categoryId,
  productType: 'SIMPLE',
  displayOrder,
  sizes: [{ id: 'unico', label, active: true, basePriceCents: price, displayOrder: 1 }],
  modifierGroupIds: [],
});

const modifier = (id, name, priceCents, displayOrder, options = {}) => ({
  id,
  name,
  active: true,
  available: true,
  priceCents,
  premium: false,
  maxQuantity: 3,
  allergenKeys: [],
  displayOrder,
  ...options,
});

const extraGroup = (id, name, modifierIds, displayOrder, maxSelections = 12) => ({
  id,
  name,
  description: 'Adicione quantos quiser; cada unidade é cobrada.',
  active: true,
  required: false,
  minSelections: 0,
  maxSelections,
  allowDuplicate: true,
  maxPerModifier: 3,
  displayOrder,
  pricingMode: 'individual',
  modifierIds,
});

export const storePublicConfigSeed = {
  storeName: 'Açaí + Sabor',
  instagramHandle: '@acaimaissabor.stafedosul',
  address: 'Endereço pendente de confirmação',
  city: 'Santa Fé do Sul/SP',
  whatsappEnabled: false,
  orderingEnabled: true,
  pauseMessage: 'No momento, estamos fora do horário de entrega.',
  enforceHours: true,
  timezone: 'America/Sao_Paulo',
  hours: [
    { day: 0, closed: false, windows: [{ open: '15:00', close: '21:50' }] },
    ...[1, 2, 3, 4, 5, 6].map((day) => ({ day, closed: false, windows: [{ open: '14:00', close: '21:50' }] })),
  ],
  holidayDates: [],
  holidayHours: [{ open: '15:00', close: '21:50' }],
  fulfillmentModes: ['PICKUP', 'DELIVERY'],
  paymentMethods: ['PIX', 'CARD', 'CASH'],
  deliveryConfig: { mode: 'FIXED', fixedFeeCents: 400 },
  orderInstructions: 'Faça seu pedido e informe o endereço, a forma de pagamento e, caso precise, o valor para troco.',
  deliveryEstimate: 'O tempo de entrega varia de 30 a 40 minutos.',
  busyDeliveryEstimate: 'Aos finais de semana e feriados, o prazo pode ser de 60 minutos ou mais.',
  holidayHoursNote: 'Em feriados, entregamos das 15:00 às 21:50.',
  gratitudeMessage: 'Estamos à disposição! Somos gratos por essa troca! 🙏🏻🙏🏻🙏🏻',
  privacyNotice: 'Seus dados são usados apenas para preparar e entregar este pedido. Política final pendente de revisão.',
  status: 'ACTIVE',
};

export const menuCatalog = {
  categories: [
    { id: 'monte-seu-copo', name: 'Monte seu copo', active: true, displayOrder: 1 },
    { id: 'combinados', name: 'Combinados', active: true, displayOrder: 2 },
    { id: 'milk-shakes', name: 'Milk-shakes', active: true, displayOrder: 3 },
    { id: 'sorvetes', name: 'Sorvetes', active: true, displayOrder: 4 },
    { id: 'shakes-acai', name: 'Shake açaí', active: true, displayOrder: 5 },
    { id: 'salada-frutas', name: 'Salada de frutas', active: true, displayOrder: 6 },
    { id: 'bebidas', name: 'Bebidas', active: true, displayOrder: 7 },
  ],
  products: [
    {
      id: 'acai-monte-seu',
      name: 'Monte seu copo',
      slug: 'monte-seu-copo',
      description: 'Escolha o sabor, o tamanho e acrescente seus acompanhamentos favoritos.',
      active: true,
      categoryId: 'monte-seu-copo',
      productType: 'CUSTOMIZABLE',
      imageUrl: '/development-acai-placeholder.png',
      displayOrder: 1,
      sizes: fourSizes([1400, 1500, 1600, 1900]),
      modifierGroupIds: ['sabores-base', ...accompanimentGroupIds, 'embalagem'],
    },
    combo('barbie', 'Barbie', 'Mousse de morango, sorvete de morango e beijinho', [2300, 2400, 2500, 2800], 1),
    combo('banana-ball', 'Banana Ball', 'Banana e Nescau Ball', [1900, 2000, 2100, 2400], 2),
    combo('beijinho', 'Beijinho', 'Beijinho, leite em pó e mousse de morango', [2200, 2300, 2400, 2700], 3),
    combo('bem-casado', 'Bem Casado', 'Brigadeiro e beijinho', [1950, 2050, 2150, 2450], 4),
    combo('chocomaster', 'Chocomaster', 'Creme de avelã, Ovomaltine e chocolate Alpino', [2450, 2550, 2650, 2950], 5),
    combo('dos-sonhos', 'Dos Sonhos', 'Sonho de Valsa, Ouro Branco e sorvete de morango', [2200, 2300, 2400, 2700], 6),
    combo('favorito', 'Favorito', 'Morango, creme de avelã e leite em pó', [2450, 2550, 2650, 2950], 7),
    combo('power', 'Power', 'Whey, banana, granola tradicional e mel', [2550, 2650, 2750, 3050], 8),
    combo('raspas', 'Raspas', 'Leite condensado, raspas de chocolate e morango', [2200, 2300, 2400, 2700], 9),
    combo('saboroso', 'Saboroso', 'Banana, leite condensado e leite em pó', [2050, 2150, 2250, 2550], 10),
    combo('jade', 'Jade', 'Ovomaltine, leite condensado e uva', [2100, 2200, 2300, 2600], 11),
    combo('pistache-berry', 'Pistache Berry', 'Pistache e morango', [2400, 2500, 2600, 2900], 12),
    combo('yogo-top', 'Yogo Top', 'Iogurte, mousse de morango e creme de avelã', [2150, 2250, 2350, 2650], 13, 'Combinado exclusivo de iogurte'),
    combo('joaninha', 'Joaninha', 'Mousse de morango e gotas de chocolate', [1950, 2050, 2150, 2450], 14),
    combo('kids-1', 'Kids I', 'Confeti, brigadeiro e chantilly', [2200, 2300, 2400, 2700], 15),
    combo('kids-2', 'Kids II', 'Confeti, leite condensado e morango', [2200, 2300, 2400, 2700], 16),
    combo('mais-sabor', 'Mais Sabor', 'Leite condensado, leite em pó, morango e granola', [2400, 2500, 2600, 2900], 17),
    combo('manila', 'Manila', 'Leite condensado, leite em pó e morango', [2150, 2250, 2350, 2650], 18),
    combo('moranguete', 'Moranguete', 'Moranguete, creme de avelã e mousse de morango', [2400, 2500, 2600, 2900], 19),
    combo('prestigio', 'Prestígio', 'Prestígio, raspas de coco, raspas de chocolate e leite condensado', [2400, 2500, 2600, 2900], 20),
    combo('supreme', 'Supreme', 'Óreo e creme de Ninho', [2200, 2300, 2400, 2700], 21),
    combo('tropical', 'Tropical', 'Abacaxi, mamão, manga e banana', [2300, 2400, 2500, 2800], 22),
    combo('220-volts', '220 Volts', 'Xarope de guaraná, Charge e paçoca', [2100, 2200, 2300, 2600], 23),
    combo('santa-fe', 'Santa Fé', 'Leite em pó, leite condensado e creme de avelã', [2300, 2400, 2500, 2800], 24),
    combo('explosao-de-oreo', 'Explosão de Óreo', 'Óreo, creme de Óreo e Ovomaltine', [2450, 2550, 2650, 2950], 25),
    combo('nuvem', 'Nuvem', 'Iogurte, mousse de Ninho e raspa de chocolate', [2000, 2100, 2200, 2500], 26, 'Combinado exclusivo de iogurte'),
    {
      id: 'milk-shake',
      name: 'Milk-shake',
      slug: 'milk-shake',
      description: 'Escolha um sabor. Cada sabor adicional custa R$ 2,50; pistache tem acréscimo de R$ 2,00.',
      active: true,
      categoryId: 'milk-shakes',
      productType: 'CUSTOMIZABLE',
      displayOrder: 1,
      sizes: threeSizes([1350, 1450, 1550], 1),
      modifierGroupIds: ['sabores-milk-shake'],
    },
    {
      id: 'sorvete',
      name: 'Sorvete',
      slug: 'sorvete',
      description: 'Escolha até 2 sabores.',
      active: true,
      categoryId: 'sorvetes',
      productType: 'CUSTOMIZABLE',
      displayOrder: 1,
      sizes: threeSizes([1500, 1600, 1700], 2),
      modifierGroupIds: ['sabores-sorvete'],
    },
    simple('shake-acai-banana-whey', 'Açaí, banana e whey', 'Shake de açaí com banana e whey.', 'shakes-acai', '500 ml', 2300, 1),
    simple('shake-acai-morango', 'Açaí e morango', 'Shake de açaí com morango.', 'shakes-acai', '500 ml', 2000, 2),
    simple('shake-acai-banana', 'Açaí e banana', 'Shake de açaí com banana.', 'shakes-acai', '500 ml', 2000, 3),
    simple('salada-de-frutas', 'Salada de frutas', 'Banana, morango, kiwi e uva.', 'salada-frutas', '300 ml', 1600, 1),
    simple('agua-sem-gas', 'Água sem gás', 'Bebida gelada.', 'bebidas', 'Unidade', 350, 1),
    simple('agua-com-gas', 'Água com gás', 'Bebida gelada.', 'bebidas', 'Unidade', 400, 2),
    simple('refrigerante', 'Refrigerante', 'Consulte os sabores disponíveis.', 'bebidas', 'Unidade', 500, 3),
  ],
  groups: [
    {
      id: 'sabores-base',
      name: 'Sabor do copo',
      description: 'Escolha 1 sabor.',
      active: true,
      required: true,
      minSelections: 1,
      maxSelections: 1,
      allowDuplicate: false,
      displayOrder: 1,
      pricingMode: 'includedQuota',
      modifierIds: ['base-acai', 'base-cupuacu', 'base-iogurte', 'base-graviola', 'base-pitaya', 'base-acai-zero'],
    },
    extraGroup('mousses', 'Mousses', ['mousse-chocolate', 'mousse-limao', 'mousse-maracuja', 'mousse-morango', 'mousse-ninho'], 10),
    extraGroup('suplementos', 'Suplemento', ['whey-protein'], 20, 5),
    extraGroup('frutas', 'Frutas', ['fruta-abacaxi', 'fruta-banana', 'fruta-cereja', 'fruta-kiwi', 'fruta-mamao', 'fruta-manga', 'fruta-morango', 'fruta-pessego', 'fruta-uva'], 30),
    extraGroup('coberturas', 'Coberturas', ['cobertura-caramelo', 'cobertura-chocolate', 'cobertura-frutas-vermelhas', 'cobertura-maracuja', 'cobertura-menta', 'cobertura-morango', 'cobertura-fini'], 40),
    extraGroup('sorvetes-adicionais', 'Sorvetes como acompanhamento', ['sorvete-bombom-extra', 'sorvete-morango-extra', 'sorvete-ninho-trufado-extra'], 50, 6),
    extraGroup('granola', 'Granola', ['granola-tradicional'], 60, 5),
    extraGroup('chocolates', 'Chocolates', ['chocolate-alpino', 'chocolate-bis-branco', 'chocolate-bis-preto', 'chocolate-brigadeiro', 'chocolate-charge', 'chocolate-confete', 'chocolate-creme-avela', 'chocolate-creme-oreo', 'chocolate-creme-ovomaltine', 'chocolate-gotas', 'chocolate-granulado', 'chocolate-kinder-bueno-white', 'chocolate-kit-kat', 'chocolate-laka', 'chocolate-moranguete', 'chocolate-nescau-ball', 'chocolate-nutella', 'chocolate-oreo', 'chocolate-ouro-branco', 'chocolate-ovomaltine', 'chocolate-power-ball-misto', 'chocolate-prestigio', 'chocolate-raspas', 'chocolate-sonho-de-valsa'], 70, 20),
    extraGroup('diversos', 'Diversos', ['diverso-amendoim', 'diverso-beijinho', 'diverso-castanha-caju', 'diverso-chantilly', 'diverso-creme-ninho', 'diverso-doce-leite', 'diverso-leite-condensado', 'diverso-creme-pistache', 'diverso-leite-po', 'diverso-mel', 'diverso-neston', 'diverso-pacoca', 'diverso-raspa-coco', 'diverso-sucrilhos', 'diverso-xarope-guarana'], 80, 18),
    {
      id: 'embalagem',
      name: 'Embalagem',
      description: 'Opcional.',
      active: true,
      required: false,
      minSelections: 0,
      maxSelections: 1,
      allowDuplicate: false,
      displayOrder: 90,
      pricingMode: 'individual',
      modifierIds: ['embalagem-viagem'],
    },
    {
      id: 'sabores-milk-shake',
      name: 'Sabores',
      description: '1 sabor incluído; sabores adicionais +R$ 2,50 cada.',
      active: true,
      required: true,
      minSelections: 1,
      maxSelections: 6,
      allowDuplicate: false,
      displayOrder: 1,
      pricingMode: 'includedQuota',
      modifierIds: ['milk-acai', 'milk-beijinho', 'milk-brigadeiro', 'milk-capuccino', 'milk-chocolate', 'milk-creme', 'milk-creme-avela', 'milk-cupuacu', 'milk-doce-leite', 'milk-ferrero-rocher', 'milk-kinder-ovo', 'milk-maracuja', 'milk-morango', 'milk-ninho', 'milk-ovomaltine', 'milk-pacoca', 'milk-prestigio', 'milk-sensacao', 'milk-pistache'],
    },
    {
      id: 'sabores-sorvete',
      name: 'Sabores',
      description: 'Escolha 1 ou 2 sabores.',
      active: true,
      required: true,
      minSelections: 1,
      maxSelections: 2,
      allowDuplicate: false,
      displayOrder: 1,
      pricingMode: 'includedQuota',
      modifierIds: ['bola-maracuja', 'bola-milho', 'bola-cafe-chocolate', 'bola-chocolate-belga', 'bola-pistache', 'bola-morango', 'bola-flocos', 'bola-unicornio', 'bola-nutellissimo', 'bola-ninho-trufado', 'bola-iogurte-amarena', 'bola-prestigio', 'bola-bombom'],
    },
  ],
  modifiers: [
    modifier('base-acai', 'Açaí', 0, 1, { maxQuantity: 1 }),
    modifier('base-cupuacu', 'Cupuaçu', 0, 2, { maxQuantity: 1 }),
    modifier('base-iogurte', 'Iogurte', 0, 3, { maxQuantity: 1 }),
    modifier('base-graviola', 'Graviola', 0, 4, { maxQuantity: 1 }),
    modifier('base-pitaya', 'Pitaya', 0, 5, { maxQuantity: 1 }),
    modifier('base-acai-zero', 'Açaí zero açúcar', 0, 6, { maxQuantity: 1 }),
    modifier('mousse-chocolate', 'Chocolate', 350, 1),
    modifier('mousse-limao', 'Limão', 300, 2),
    modifier('mousse-maracuja', 'Maracujá', 300, 3),
    modifier('mousse-morango', 'Morango', 300, 4),
    modifier('mousse-ninho', 'Ninho', 350, 5),
    modifier('whey-protein', 'Whey protein', 550, 1),
    modifier('fruta-abacaxi', 'Abacaxi', 250, 1),
    modifier('fruta-banana', 'Banana', 250, 2),
    modifier('fruta-cereja', 'Cereja', 400, 3),
    modifier('fruta-kiwi', 'Kiwi', 350, 4),
    modifier('fruta-mamao', 'Mamão', 200, 5),
    modifier('fruta-manga', 'Manga', 250, 6),
    modifier('fruta-morango', 'Morango', 350, 7),
    modifier('fruta-pessego', 'Pêssego', 300, 8),
    modifier('fruta-uva', 'Uva', 300, 9),
    modifier('cobertura-caramelo', 'Caramelo', 150, 1),
    modifier('cobertura-chocolate', 'Chocolate', 150, 2),
    modifier('cobertura-frutas-vermelhas', 'Frutas vermelhas', 150, 3),
    modifier('cobertura-maracuja', 'Maracujá', 150, 4),
    modifier('cobertura-menta', 'Menta', 150, 5),
    modifier('cobertura-morango', 'Morango', 150, 6),
    modifier('cobertura-fini', 'Fini', 250, 7),
    modifier('sorvete-bombom-extra', 'Bombom', 350, 1),
    modifier('sorvete-morango-extra', 'Morango', 350, 2),
    modifier('sorvete-ninho-trufado-extra', 'Ninho trufado', 350, 3),
    modifier('granola-tradicional', 'Tradicional', 250, 1),
    modifier('chocolate-alpino', 'Alpino', 350, 1),
    modifier('chocolate-bis-branco', 'Bis Branco', 200, 2),
    modifier('chocolate-bis-preto', 'Bis Preto', 200, 3),
    modifier('chocolate-brigadeiro', 'Brigadeiro', 300, 4),
    modifier('chocolate-charge', 'Charge', 300, 5),
    modifier('chocolate-confete', 'Confete', 300, 6),
    modifier('chocolate-creme-avela', 'Creme de avelã', 500, 7),
    modifier('chocolate-creme-oreo', 'Creme de Óreo', 500, 8),
    modifier('chocolate-creme-ovomaltine', 'Creme de Ovomaltine', 500, 9),
    modifier('chocolate-gotas', 'Gotas de chocolate', 300, 10),
    modifier('chocolate-granulado', 'Granulado', 250, 11),
    modifier('chocolate-kinder-bueno-white', 'Kinder Bueno White', 900, 12),
    modifier('chocolate-kit-kat', 'Kit Kat', 300, 13),
    modifier('chocolate-laka', 'Laka', 350, 14),
    modifier('chocolate-moranguete', 'Moranguete', 250, 15),
    modifier('chocolate-nescau-ball', 'Nescau Ball', 300, 16),
    modifier('chocolate-nutella', 'Nutella', 900, 17),
    modifier('chocolate-oreo', 'Óreo', 350, 18),
    modifier('chocolate-ouro-branco', 'Ouro Branco', 250, 19),
    modifier('chocolate-ovomaltine', 'Ovomaltine', 250, 20),
    modifier('chocolate-power-ball-misto', 'Power Ball Misto', 300, 21),
    modifier('chocolate-prestigio', 'Prestígio', 350, 22),
    modifier('chocolate-raspas', 'Raspas de chocolate', 300, 23),
    modifier('chocolate-sonho-de-valsa', 'Sonho de Valsa', 250, 24),
    modifier('diverso-amendoim', 'Amendoim', 200, 1),
    modifier('diverso-beijinho', 'Beijinho', 300, 2),
    modifier('diverso-castanha-caju', 'Castanha de caju', 350, 3),
    modifier('diverso-chantilly', 'Chantilly', 250, 4),
    modifier('diverso-creme-ninho', 'Creme de Ninho', 500, 5),
    modifier('diverso-doce-leite', 'Doce de leite', 250, 6),
    modifier('diverso-leite-condensado', 'Leite condensado', 200, 7),
    modifier('diverso-creme-pistache', 'Creme de pistache', 700, 8),
    modifier('diverso-leite-po', 'Leite em pó', 250, 9),
    modifier('diverso-mel', 'Mel', 150, 10),
    modifier('diverso-neston', 'Neston', 250, 11),
    modifier('diverso-pacoca', 'Paçoca', 250, 12),
    modifier('diverso-raspa-coco', 'Raspa de coco', 200, 13),
    modifier('diverso-sucrilhos', 'Sucrilhos', 200, 14),
    modifier('diverso-xarope-guarana', 'Xarope de guaraná', 200, 15),
    modifier('embalagem-viagem', 'Embalagem para viagem', 100, 1, { maxQuantity: 1 }),
    ...['Açaí', 'Beijinho', 'Brigadeiro', 'Capuccino', 'Chocolate', 'Creme', 'Creme de avelã', 'Cupuaçu', 'Doce de leite', 'Ferrero Rocher', 'Kinder Ovo', 'Maracujá', 'Morango', 'Ninho', 'Ovomaltine', 'Paçoca', 'Prestígio', 'Sensação'].map((name, index) => modifier(`milk-${['acai', 'beijinho', 'brigadeiro', 'capuccino', 'chocolate', 'creme', 'creme-avela', 'cupuacu', 'doce-leite', 'ferrero-rocher', 'kinder-ovo', 'maracuja', 'morango', 'ninho', 'ovomaltine', 'pacoca', 'prestigio', 'sensacao'][index]}`, name, 250, index + 1, { maxQuantity: 1 })),
    modifier('milk-pistache', 'Pistache', 200, 19, { premium: true, maxQuantity: 1 }),
    ...['Maracujá', 'Milho', 'Café com chocolate', 'Chocolate belga', 'Pistache', 'Morango', 'Flocos', 'Unicórnio', 'Nutellíssimo', 'Ninho trufado', 'Iogurte com amarena', 'Prestígio', 'Bombom'].map((name, index) => modifier(`bola-${['maracuja', 'milho', 'cafe-chocolate', 'chocolate-belga', 'pistache', 'morango', 'flocos', 'unicornio', 'nutellissimo', 'ninho-trufado', 'iogurte-amarena', 'prestigio', 'bombom'][index]}`, name, 0, index + 1, { maxQuantity: 1 })),
  ],
};
